apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringMetricDescriptor
metadata:
  name: nginx-requests-processed
  namespace: nginx-apps
spec:
  projectRef:
    external: "mcp-lud-wew"
  # All custom metrics in GCP must start with custom.googleapis.com/
  type: custom.googleapis.com/nginx/requests_processed
  displayName: "Nginx Processed Requests"
  description: "Tracks the number of requests processed by the Nginx application, separated by canary version."
  
  # CUMULATIVE is best for counting increasing totals over time
  metricKind: CUMULATIVE 
  valueType: INT64 
  unit: "1" 
  
  # These labels allow you to compare v1 (90%) vs v2 (10%) in your dashboards
  labels:
    - key: "version"
      valueType: STRING
      description: "The version of the deployment handling the request (e.g., v1 or v2)"
    - key: "http_status"
      valueType: STRING
      description: "The HTTP status code returned"
